# 必读！！！
# 此版本没有做防泄露处理，如介意请使用另一个名字为configdns的版本
# 注意规则在满足自己需求情况下，尽量做到精简，不要过度复杂，以免影响性能。
# 跑裸核用户请自行去掉下方控制面板模块的注释。

# ※※※※※※※※※※※※※※※ 锚点区域 ※※※※※※※※※※※※※※※
# ① 订阅锚点
Anchor_PR:
  &Anchor_PR {
    type: http,
    interval: 86400,
    proxy: 直连,
    health-check:
      { enable: true, url: "https://www.g.cn/generate_204", interval: 300 },
  }

# ※※※※※※※※※※※※※※※ 节点订阅 ※※※※※※※※※※※※※※※
# 将 “订阅链接” 与 “机场名” 替换为所用机场信息； 订阅条数不够可新增，注意开头缩进，不同条数前方 “机场名” 不能重复； 末尾的 “机场名” 作用为每个节点添加机场名称前缀，可自定义。
proxy-providers:
  跑路云:
    {
      <<: *Anchor_PR,
      url: "订阅链接",
      override: { additional-prefix: "[跑路云] " },
    }
  小姨子:
    {
      <<: *Anchor_PR,
      url: "订阅链接",
      override: { additional-prefix: "[小姨子] " },
    }
  小姨子v6:
    {
      <<: *Anchor_PR,
      url: "订阅链接",
      override: { additional-prefix: "[小姨子v6] " },
    }

# 节点信息
proxies:
  - name: "[落地] - 加州圣何塞"
    dialer-proxy: "加州圣何塞前置节点"
    type: socks5
    server: xxx
    port: 443
    username: xxx
    password: xxx
    skip-cert-verify: true
    udp: true
  - name: "[落地] - aaitr"
    dialer-proxy: "aaitr前置节点"
    type: ss
    server: xxx
    port: 443
    cipher: xxx
    password: xxx
    udp: false
  - { name: 直连, type: direct }

# 全局配置
mixed-port: 7890
allow-lan: true
mode: rule
bind-address: "*"
ipv6: true
unified-delay: true
tcp-concurrent: true
log-level: warning
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true
clash-for-android:
  append-system-dns: false

# 为防止使用插件朋友遇到面板问题，我注释掉了此模块。
# external-controller: 0.0.0.0:9090
# secret: ""
# external-ui: ui
# external-ui-name: zashboard
# external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip

# 嗅探（fakeip下其实可以不用嗅探）
sniffer:
  enable: true # 启用嗅探  提升分流准确性
  override-destination: true # 成功解析  使用嗅探到的域名覆盖原始目标地址
  parse-pure-ip: true # 反向解析  解析纯 IP 连接（尝试反向解析获得域名）
  force-dns-mapping: true # 强制映射  DNS 映射（对纯 IP 连接尝试 DNS 映射）
  sniff:
    QUIC:
      ports: [443] # 嗅探参数  QUIC 协议流量（HTTP/3 常用端口）
    TLS:
      ports: [443, 8443] # 嗅探参数  HTTPS（TLS）常用及备用端口
    HTTP:
      ports: [80, 8080-8880] # 嗅探参数  HTTP 及常见 Web / 代理端口段
      override-destination: true # 嗅探成功  HTTP 嗅探成功后覆盖目标地址
  force-domain:
    - "+.netflix.com" # 强制嗅探  Netflix 主域名
    - "+.nflxvideo.net" # 强制嗅探  Netflix CDN
    - "+.amazonaws.com" # 强制嗅探  AWS 云服务
    - "+.media.dssott.com" # 强制嗅探  Disney+ 流媒体
  skip-domain:
    - "+.apple.com" # 跳过嗅探  苹果服务
    - Mijia Cloud # 跳过嗅探  米家云服务
    - dlg.io.mi.com # 跳过嗅探  小米设备通信
    - "+.oray.com" # 跳过嗅探  花生壳服务
    - "+.sunlogin.net" # 跳过嗅探  向日葵远程控制
    - "+.push.apple.com" # 跳过嗅探  苹果推送服务

# 入站
tun:
  enable: true # 网卡模式  是否启用 TUN 虚拟网卡模式
  stack: mixed # 协议类型  网络栈：system（系统栈）/ gvisor（内置用户态栈）/ mixed（混合）
  dns-hijack: ["any:53", "tcp://any:53"] # 劫持请求  劫持所有 UDP/TCP 53 端口的 DNS 请求
  auto-detect-interface: true # 自动出口  自动识别默认出口网络接口 （仅内核模式有效）
  auto-route: true # 自动路由  自动添加系统路由表      （仅内核模式有效）
  auto-redirect: false # 自动定向  自动将流量重定向至 TUN  （仅内核模式有效）
  strict-route: false # 路由模式  严格路由模式
  endpoint-independent-nat: true # 端点无关  NAT（提高 NAT 类型兼容性，适用于 P2P 和游戏）

# DNS模块
dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:1053
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:fakeipfilter_domain"
  default-nameserver:
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

# 出站策略，根据自己情况调整每个策略里分组排序，增删都可以，比如把美国自动放到第一个，比如删除香港故转，注意别漏掉表情逗号等。
# 如果相应分组没有筛选到对应的国家，请根据自己节点名字调整筛选关键字。
# 没有再使用锚点，是考虑很多新手修改难度，这样新手修改某个分组更容易些。
proxy-groups:
  - {
      name: 🚀 默认代理,
      type: select,
      proxies:
        [
          🔯 美国故转,
          aaitr,
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 📹 YouTube,
      type: select,
      proxies:
        [
          🔯 美国故转,
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          ♻️ 美国自动,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
          aaitr,
        ],
    }
  - {
      name: 🍀 Google,
      type: select,
      proxies:
        [
          aaitr,
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 🤖 ChatGPT,
      type: select,
      proxies:
        [
          aaitr,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 👨🏿‍💻 GitHub,
      type: select,
      proxies:
        [
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
          aaitr,
        ],
    }
  - {
      name: 🐬 OneDrive,
      type: select,
      proxies:
        [
          ♻️ 香港自动,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
          aaitr,
        ],
    }
  - {
      name: 🪟 Microsoft,
      type: select,
      proxies:
        [
          ♻️ 香港自动,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
          aaitr,
        ],
    }
  - {
      name: 🎵 TikTok,
      type: select,
      proxies:
        [
          aaitr,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 📲 Telegram,
      type: select,
      proxies:
        [
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
          aaitr,
        ],
    }
  - {
      name: 🎥 NETFLIX,
      type: select,
      proxies:
        [
          🔯 美国故转,
          🔯 狮城故转,
          🔯 香港故转,
          🔯 日本故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
          aaitr,
        ],
    }
  - {
      name: 💶 PayPal,
      type: select,
      proxies:
        [
          aaitr,
          🔯 日本故转,
          🔯 香港故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 🐟 漏网之鱼,
      type: select,
      proxies:
        [
          🚀 默认代理,
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
          aaitr,
        ],
    }
  - {
      name: 🇭🇰 香港节点,
      type: select,
      include-all: true,
      filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$",
    }
  - {
      name: 🇯🇵 日本节点,
      type: select,
      include-all: true,
      filter: "(?=.*(日|东京|JP|(?i)Japan))^((?!(港|台|韩|新|美|尼)).)*$",
    }
  - {
      name: 🇸🇬 狮城节点,
      type: select,
      include-all: true,
      filter: "(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(台|日|韩|深|美)).)*$",
    }
  - {
      name: 🇺🇲 美国节点,
      type: select,
      include-all: true,
      filter: "(?=.*(美|波特兰|US|(?i)States|America))^((?!(港|台|韩|新|日)).)*$",
    }
  - {
      name: 🔯 香港故转,
      type: fallback,
      include-all: true,
      interval: 300,
      filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$",
    }
  - {
      name: 🔯 日本故转,
      type: fallback,
      include-all: true,
      interval: 300,
      filter: "(?=.*(日|东京|JP|(?i)Japan))^((?!(港|台|韩|新|美|尼)).)*$",
    }
  - {
      name: 🔯 狮城故转,
      type: fallback,
      include-all: true,
      interval: 300,
      filter: "(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(台|日|韩|深|美)).)*$",
    }
  - {
      name: 🔯 美国故转,
      type: fallback,
      include-all: true,
      interval: 300,
      filter: "(?=.*(美|波特兰|US|(?i)States|America))^((?!(港|台|韩|新|日)).)*$",
    }
  - {
      name: ♻️ 香港自动,
      type: url-test,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$",
    }
  - {
      name: ♻️ 日本自动,
      type: url-test,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?=.*(日|东京|JP|(?i)Japan))^((?!(港|台|韩|新|美|尼)).)*$",
    }
  - {
      name: ♻️ 狮城自动,
      type: url-test,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(港|台|韩|日|美)).)*$",
    }
  - {
      name: ♻️ 美国自动,
      type: url-test,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?=.*(美|波特兰|US|(?i)States|America))^((?!(港|台|日|韩|新)).)*$",
    }
  - {
      name: ♻️ 自动选择,
      type: url-test,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "^((?!(直连)).)*$",
    }
  - {
      name: "加州圣何塞前置节点",
      type: load-balance,
      url: "https://www.gstatic.com/generate_204",
      interval: 10,
      lazy: false,
      timeout: 1000,
      max-failed-times: 5,
      disable-udp: false,
      include-all: true,
      filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$",
      strategy: round-robin,
    }
  - {
      name: "aaitr前置节点",
      type: select,
      url: "https://www.gstatic.com/generate_204",
      interval: 300,
      max-failed-times: 5,
      disable-udp: true,
      include-all: true,
      filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$",
    }
  - {
      name: "手动选择（7903）",
      type: select,
      proxies: [DIRECT],
      url: "https://www.gstatic.com/generate_204",
      interval: 300,
      max-failed-times: 5,
      include-all: true,
      filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$",
    }
  - { name: aaitr, type: select, proxies: ["[落地] - aaitr"] }
  - { name: 🌐 全部节点, type: select, include-all: true }

# 规则匹配
rules:
  - RULE-SET,private_ip,直连,no-resolve
  - RULE-SET,private_domain,直连
  - DOMAIN-SUFFIX,qichiyu.com,🚀 默认代理
  - RULE-SET,proxylite,🚀 默认代理
  - RULE-SET,ai,🤖 ChatGPT
  - RULE-SET,github_domain,👨🏿‍💻 GitHub
  - RULE-SET,youtube_domain,📹 YouTube
  - RULE-SET,google_domain,🍀 Google
  - RULE-SET,onedrive_domain,🐬 OneDrive
  - RULE-SET,microsoft_domain,🪟 Microsoft
  - RULE-SET,apple_domain,直连
  - RULE-SET,tiktok_domain,🎵 TikTok
  - RULE-SET,telegram_domain,📲 Telegram
  - RULE-SET,netflix_domain,🎥 NETFLIX
  - RULE-SET,paypal_domain,💶 PayPal
  - RULE-SET,apple_ip,直连
  - RULE-SET,google_ip,🍀 Google
  - RULE-SET,netflix_ip,🎥 NETFLIX
  - RULE-SET,telegram_ip,📲 Telegram
  - RULE-SET,geolocation-!cn,🚀 默认代理
  - RULE-SET,cn_domain,直连
  - RULE-SET,cn_ip,直连
  - MATCH,🐟 漏网之鱼

# 规则集
## type：可选http/file/inline  behavior：可选domain/ipcidr/classical format：可选yaml/text/mrs
rule-anchor:
  ip: &ip { type: http, interval: 86400, behavior: ipcidr, format: mrs }
  domain: &domain { type: http, interval: 86400, behavior: domain, format: mrs }
  class:
    &class { type: http, interval: 86400, behavior: classical, format: text }
rule-providers:
  fakeipfilter_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs",
    }
  private_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs",
    }
  proxylite:
    {
      <<: *class,
      url: "https://raw.githubusercontent.com/qqqasdwx/rule/refs/heads/main/proxy.list",
    }
  ai:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs",
    }
  youtube_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs",
    }
  google_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs",
    }
  github_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs",
    }
  telegram_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs",
    }
  netflix_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs",
    }
  paypal_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs",
    }
  onedrive_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs",
    }
  microsoft_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs",
    }
  apple_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs",
    }
  speedtest_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs",
    }
  tiktok_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs",
    }
  geolocation-!cn:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs",
    }
  cn_domain:
    {
      <<: *domain,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs",
    }

  private_ip:
    {
      <<: *ip,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs",
    }
  cn_ip:
    {
      <<: *ip,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs",
    }
  google_ip:
    {
      <<: *ip,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs",
    }
  telegram_ip:
    {
      <<: *ip,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs",
    }
  netflix_ip:
    {
      <<: *ip,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs",
    }
  apple_ip:
    {
      <<: *ip,
      url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs",
    }
listeners:
  - name: "Inbound-7902"
    type: mixed
    port: 7902
    listen: 0.0.0.0
    proxy: "[落地] - 加州圣何塞"
  - name: "Inbound-7903"
    type: mixed
    port: 7903
    listen: 0.0.0.0
    proxy: "手动选择（7903）"
  - name: "Inbound-7904"
    type: mixed
    port: 7904
    listen: 0.0.0.0
    proxy: "[落地] - aaitr"
